### ISSUE TITLE
Benutzeraccounts elastic.io anlegen

### ISSUE THREAD

**Issue by FranzDegenhardt** [openintegrationhub/coordination#2]
Für die folgenden Benutzer müssen Accounts für die elastic.io Plattform angelegt werden:
- Hans-Jörg
- Joseph

## Aktzeptanzkriterien
- Benutzername und Passwort werden angelegt
- Benutzername und Passwort sind den jeweiligen Benutzern bekannt

## Definition of Done
- Die Benutzer können sich auf der elastic.io Plattform anmelden

**Comment by drobiazko** [comment]
Accounts have been created and both are invited.

**Comment by zubairov** [comment]
I'll close this issue then.
